// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaigonRideProject.Data;

#nullable disable

namespace SaigonRideProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260427093239_update battery")]
    partial class updatebattery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SaigonRideProject.Models.OtpVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Email", "OtpCode");

                    b.ToTable("OtpVerifications");
                });

            modelBuilder.Entity("SaigonRideProject.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QrCodeUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RentalId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id");

                    b.HasIndex("RentalId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SaigonRideProject.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PickupStationId")
                        .HasColumnType("int");

                    b.Property<int?>("ReturnStationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PickupStationId");

                    b.HasIndex("ReturnStationId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[Status] = 'InProgress'");

                    b.HasIndex("VehicleId");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("SaigonRideProject.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("CurrentInventory")
                        .HasColumnType("int");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "District 1",
                            Capacity = 20,
                            CurrentInventory = 0,
                            Latitude = 10.772,
                            Longitude = 106.69799999999999,
                            Name = "Ben Thanh Station",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Vo Van Tan",
                            Capacity = 18,
                            CurrentInventory = 0,
                            Latitude = 10.782500000000001,
                            Longitude = 106.69,
                            Name = "District 3 Hub",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Dien Bien Phu",
                            Capacity = 18,
                            CurrentInventory = 0,
                            Latitude = 10.803100000000001,
                            Longitude = 106.715,
                            Name = "Binh Thanh Station",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Vo Nguyen Giap",
                            Capacity = 25,
                            CurrentInventory = 0,
                            Latitude = 10.85,
                            Longitude = 106.77,
                            Name = "Thu Duc Station",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Cong Hoa",
                            Capacity = 18,
                            CurrentInventory = 0,
                            Latitude = 10.801,
                            Longitude = 106.652,
                            Name = "Tan Binh Station",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Nguyen Van Linh",
                            Capacity = 18,
                            CurrentInventory = 0,
                            Latitude = 10.7295,
                            Longitude = 106.721,
                            Name = "District 7 Station",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Phan Xich Long",
                            Capacity = 15,
                            CurrentInventory = 0,
                            Latitude = 10.798999999999999,
                            Longitude = 106.68000000000001,
                            Name = "Phu Nhuan Station",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Quang Trung",
                            Capacity = 18,
                            CurrentInventory = 0,
                            Latitude = 10.837999999999999,
                            Longitude = 106.66800000000001,
                            Name = "Go Vap Station",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("SaigonRideProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("None");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("PassportStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 0m,
                            Email = "admin@saigonride.com",
                            FullName = "System Admin",
                            IdentityImageUrl = "",
                            IdentityNumber = "000000000",
                            IdentityType = "CCCD",
                            IsLocked = false,
                            IsVerified = true,
                            PassportStatus = "Approved",
                            PasswordHash = "$2a$11$EMDNlMRrKrVFWpooIFhz7e4kh0nVVhXEUQT11DVS4DJf0RtOi5QiO",
                            Role = "Admin",
                            UserType = "Local"
                        });
                });

            modelBuilder.Entity("SaigonRideProject.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatteryLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerMinute")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("StationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatteryLevel = 100,
                            PlateNumber = "BK-001",
                            PricePerMinute = 500m,
                            StationId = 1,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 2,
                            BatteryLevel = 90,
                            PlateNumber = "BK-002",
                            PricePerMinute = 500m,
                            StationId = 1,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 3,
                            BatteryLevel = 100,
                            PlateNumber = "BK-003",
                            PricePerMinute = 500m,
                            StationId = 1,
                            Status = "InUse",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 4,
                            BatteryLevel = 85,
                            PlateNumber = "BK-004",
                            PricePerMinute = 500m,
                            StationId = 1,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 5,
                            BatteryLevel = 95,
                            PlateNumber = "SC-001",
                            PricePerMinute = 1500m,
                            StationId = 1,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 6,
                            BatteryLevel = 72,
                            PlateNumber = "SC-002",
                            PricePerMinute = 1500m,
                            StationId = 1,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 7,
                            BatteryLevel = 15,
                            PlateNumber = "SC-003",
                            PricePerMinute = 1500m,
                            StationId = 1,
                            Status = "Maintenance",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 8,
                            BatteryLevel = 100,
                            PlateNumber = "BK-101",
                            PricePerMinute = 500m,
                            StationId = 2,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 9,
                            BatteryLevel = 88,
                            PlateNumber = "BK-102",
                            PricePerMinute = 500m,
                            StationId = 2,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 10,
                            BatteryLevel = 100,
                            PlateNumber = "BK-103",
                            PricePerMinute = 500m,
                            StationId = 2,
                            Status = "InUse",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 11,
                            BatteryLevel = 92,
                            PlateNumber = "BK-104",
                            PricePerMinute = 500m,
                            StationId = 2,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 12,
                            BatteryLevel = 80,
                            PlateNumber = "SC-101",
                            PricePerMinute = 1500m,
                            StationId = 2,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 13,
                            BatteryLevel = 10,
                            PlateNumber = "SC-102",
                            PricePerMinute = 1500m,
                            StationId = 2,
                            Status = "Maintenance",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 14,
                            BatteryLevel = 77,
                            PlateNumber = "SC-103",
                            PricePerMinute = 1500m,
                            StationId = 2,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 15,
                            BatteryLevel = 100,
                            PlateNumber = "BK-201",
                            PricePerMinute = 500m,
                            StationId = 3,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 16,
                            BatteryLevel = 95,
                            PlateNumber = "BK-202",
                            PricePerMinute = 500m,
                            StationId = 3,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 17,
                            BatteryLevel = 100,
                            PlateNumber = "BK-203",
                            PricePerMinute = 500m,
                            StationId = 3,
                            Status = "InUse",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 18,
                            BatteryLevel = 89,
                            PlateNumber = "BK-204",
                            PricePerMinute = 500m,
                            StationId = 3,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 19,
                            BatteryLevel = 60,
                            PlateNumber = "SC-201",
                            PricePerMinute = 1500m,
                            StationId = 3,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 20,
                            BatteryLevel = 18,
                            PlateNumber = "SC-202",
                            PricePerMinute = 1500m,
                            StationId = 3,
                            Status = "Maintenance",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 21,
                            BatteryLevel = 91,
                            PlateNumber = "SC-203",
                            PricePerMinute = 1500m,
                            StationId = 3,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 22,
                            BatteryLevel = 100,
                            PlateNumber = "BK-301",
                            PricePerMinute = 500m,
                            StationId = 4,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 23,
                            BatteryLevel = 85,
                            PlateNumber = "BK-302",
                            PricePerMinute = 500m,
                            StationId = 4,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 24,
                            BatteryLevel = 100,
                            PlateNumber = "BK-303",
                            PricePerMinute = 500m,
                            StationId = 4,
                            Status = "InUse",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 25,
                            BatteryLevel = 93,
                            PlateNumber = "BK-304",
                            PricePerMinute = 500m,
                            StationId = 4,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 26,
                            BatteryLevel = 88,
                            PlateNumber = "SC-301",
                            PricePerMinute = 1500m,
                            StationId = 4,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 27,
                            BatteryLevel = 12,
                            PlateNumber = "SC-302",
                            PricePerMinute = 1500m,
                            StationId = 4,
                            Status = "Maintenance",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 28,
                            BatteryLevel = 74,
                            PlateNumber = "SC-303",
                            PricePerMinute = 1500m,
                            StationId = 4,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 29,
                            BatteryLevel = 100,
                            PlateNumber = "BK-401",
                            PricePerMinute = 500m,
                            StationId = 5,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 30,
                            BatteryLevel = 90,
                            PlateNumber = "BK-402",
                            PricePerMinute = 500m,
                            StationId = 5,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 31,
                            BatteryLevel = 100,
                            PlateNumber = "BK-403",
                            PricePerMinute = 500m,
                            StationId = 5,
                            Status = "InUse",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 32,
                            BatteryLevel = 88,
                            PlateNumber = "BK-404",
                            PricePerMinute = 500m,
                            StationId = 5,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 33,
                            BatteryLevel = 70,
                            PlateNumber = "SC-401",
                            PricePerMinute = 1500m,
                            StationId = 5,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 34,
                            BatteryLevel = 9,
                            PlateNumber = "SC-402",
                            PricePerMinute = 1500m,
                            StationId = 5,
                            Status = "Maintenance",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 35,
                            BatteryLevel = 82,
                            PlateNumber = "SC-403",
                            PricePerMinute = 1500m,
                            StationId = 5,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 36,
                            BatteryLevel = 100,
                            PlateNumber = "BK-501",
                            PricePerMinute = 500m,
                            StationId = 6,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 37,
                            BatteryLevel = 93,
                            PlateNumber = "BK-502",
                            PricePerMinute = 500m,
                            StationId = 6,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 38,
                            BatteryLevel = 100,
                            PlateNumber = "BK-503",
                            PricePerMinute = 500m,
                            StationId = 6,
                            Status = "InUse",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 39,
                            BatteryLevel = 87,
                            PlateNumber = "BK-504",
                            PricePerMinute = 500m,
                            StationId = 6,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 40,
                            BatteryLevel = 79,
                            PlateNumber = "SC-501",
                            PricePerMinute = 1500m,
                            StationId = 6,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 41,
                            BatteryLevel = 14,
                            PlateNumber = "SC-502",
                            PricePerMinute = 1500m,
                            StationId = 6,
                            Status = "Maintenance",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 42,
                            BatteryLevel = 90,
                            PlateNumber = "SC-503",
                            PricePerMinute = 1500m,
                            StationId = 6,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 43,
                            BatteryLevel = 100,
                            PlateNumber = "BK-601",
                            PricePerMinute = 500m,
                            StationId = 7,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 44,
                            BatteryLevel = 95,
                            PlateNumber = "BK-602",
                            PricePerMinute = 500m,
                            StationId = 7,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 45,
                            BatteryLevel = 100,
                            PlateNumber = "BK-603",
                            PricePerMinute = 500m,
                            StationId = 7,
                            Status = "InUse",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 46,
                            BatteryLevel = 85,
                            PlateNumber = "SC-601",
                            PricePerMinute = 1500m,
                            StationId = 7,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 47,
                            BatteryLevel = 17,
                            PlateNumber = "SC-602",
                            PricePerMinute = 1500m,
                            StationId = 7,
                            Status = "Maintenance",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 48,
                            BatteryLevel = 76,
                            PlateNumber = "SC-603",
                            PricePerMinute = 1500m,
                            StationId = 7,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 49,
                            BatteryLevel = 100,
                            PlateNumber = "BK-701",
                            PricePerMinute = 500m,
                            StationId = 8,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 50,
                            BatteryLevel = 92,
                            PlateNumber = "SC-701",
                            PricePerMinute = 1500m,
                            StationId = 8,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        });
                });

            modelBuilder.Entity("SaigonRideProject.Models.WalletTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("SaigonRideProject.Models.Payment", b =>
                {
                    b.HasOne("SaigonRideProject.Models.Rental", "Rental")
                        .WithMany("Payments")
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rental");
                });

            modelBuilder.Entity("SaigonRideProject.Models.Rental", b =>
                {
                    b.HasOne("SaigonRideProject.Models.Station", "PickupStation")
                        .WithMany()
                        .HasForeignKey("PickupStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaigonRideProject.Models.Station", "ReturnStation")
                        .WithMany()
                        .HasForeignKey("ReturnStationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SaigonRideProject.Models.User", "User")
                        .WithMany("Rentals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaigonRideProject.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PickupStation");

                    b.Navigation("ReturnStation");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SaigonRideProject.Models.Vehicle", b =>
                {
                    b.HasOne("SaigonRideProject.Models.Station", "Station")
                        .WithMany("Vehicles")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Station");
                });

            modelBuilder.Entity("SaigonRideProject.Models.WalletTransaction", b =>
                {
                    b.HasOne("SaigonRideProject.Models.User", "User")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SaigonRideProject.Models.Rental", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SaigonRideProject.Models.Station", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("SaigonRideProject.Models.User", b =>
                {
                    b.Navigation("Rentals");

                    b.Navigation("WalletTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
