// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaigonRideProject.Data;

#nullable disable

namespace SaigonRideProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("SaigonRideProject.Models.OtpVerification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("OtpCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email", "OtpCode");

                    b.ToTable("OtpVerifications");
                });

            modelBuilder.Entity("SaigonRideProject.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("QrCodeUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RentalId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id");

                    b.HasIndex("RentalId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SaigonRideProject.Models.Rental", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BaseAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DiscountPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("TEXT");

                    b.Property<int>("PickupStationId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReturnStationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PickupStationId");

                    b.HasIndex("ReturnStationId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[Status] = 'InProgress'");

                    b.HasIndex("VehicleId");

                    b.ToTable("Rentals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseAmount = 10000m,
                            DiscountPercent = 10m,
                            EndTime = new DateTime(2026, 5, 2, 0, 20, 0, 0, DateTimeKind.Unspecified),
                            FinalAmount = 9000m,
                            PickupStationId = 1,
                            ReturnStationId = 2,
                            StartTime = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            UserId = 2,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            BaseAmount = 15000m,
                            DiscountPercent = 0m,
                            EndTime = new DateTime(2026, 5, 1, 0, 15, 0, 0, DateTimeKind.Unspecified),
                            FinalAmount = 15000m,
                            PickupStationId = 2,
                            ReturnStationId = 3,
                            StartTime = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            UserId = 4,
                            VehicleId = 6
                        },
                        new
                        {
                            Id = 3,
                            BaseAmount = 20000m,
                            DiscountPercent = 10m,
                            EndTime = new DateTime(2026, 4, 30, 0, 30, 0, 0, DateTimeKind.Unspecified),
                            FinalAmount = 18000m,
                            PickupStationId = 3,
                            ReturnStationId = 4,
                            StartTime = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            UserId = 3,
                            VehicleId = 11
                        },
                        new
                        {
                            Id = 4,
                            BaseAmount = 0m,
                            DiscountPercent = 0m,
                            FinalAmount = 0m,
                            PickupStationId = 4,
                            ReturnStationId = 5,
                            StartTime = new DateTime(2026, 4, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Cancelled",
                            UserId = 5,
                            VehicleId = 16
                        },
                        new
                        {
                            Id = 5,
                            BaseAmount = 12000m,
                            DiscountPercent = 15m,
                            EndTime = new DateTime(2026, 4, 26, 0, 25, 0, 0, DateTimeKind.Unspecified),
                            FinalAmount = 10000m,
                            PickupStationId = 5,
                            ReturnStationId = 6,
                            StartTime = new DateTime(2026, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            UserId = 2,
                            VehicleId = 21
                        },
                        new
                        {
                            Id = 6,
                            BaseAmount = 30000m,
                            DiscountPercent = 10m,
                            EndTime = new DateTime(2026, 4, 18, 0, 40, 0, 0, DateTimeKind.Unspecified),
                            FinalAmount = 27000m,
                            PickupStationId = 6,
                            ReturnStationId = 7,
                            StartTime = new DateTime(2026, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            UserId = 4,
                            VehicleId = 26
                        },
                        new
                        {
                            Id = 7,
                            BaseAmount = 50000m,
                            DiscountPercent = 10m,
                            EndTime = new DateTime(2026, 4, 3, 0, 50, 0, 0, DateTimeKind.Unspecified),
                            FinalAmount = 45000m,
                            PickupStationId = 7,
                            ReturnStationId = 8,
                            StartTime = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Completed",
                            UserId = 3,
                            VehicleId = 31
                        });
                });

            modelBuilder.Entity("SaigonRideProject.Models.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Stations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "District 1",
                            Capacity = 25,
                            Latitude = 10.772,
                            Longitude = 106.69799999999999,
                            Name = "Ben Thanh Station",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Vo Van Tan",
                            Capacity = 26,
                            Latitude = 10.782500000000001,
                            Longitude = 106.69,
                            Name = "District 3 Hub",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Dien Bien Phu",
                            Capacity = 5,
                            Latitude = 10.803100000000001,
                            Longitude = 106.715,
                            Name = "Binh Thanh Station",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Vo Nguyen Giap",
                            Capacity = 24,
                            Latitude = 10.85,
                            Longitude = 106.77,
                            Name = "Thu Duc Station",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Cong Hoa",
                            Capacity = 22,
                            Latitude = 10.801,
                            Longitude = 106.652,
                            Name = "Tan Binh Station",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Nguyen Van Linh",
                            Capacity = 20,
                            Latitude = 10.7295,
                            Longitude = 106.721,
                            Name = "District 7 Station",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Phan Xich Long",
                            Capacity = 18,
                            Latitude = 10.798999999999999,
                            Longitude = 106.68000000000001,
                            Name = "Phu Nhuan Station",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Quang Trung",
                            Capacity = 22,
                            Latitude = 10.837999999999999,
                            Longitude = 106.66800000000001,
                            Name = "Go Vap Station",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Tran Hung Dao",
                            Capacity = 18,
                            Latitude = 10.755000000000001,
                            Longitude = 106.67,
                            Name = "District 5 Station",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Su Van Hanh",
                            Capacity = 18,
                            Latitude = 10.7705,
                            Longitude = 106.66500000000001,
                            Name = "District 10 Station",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Lu Gia",
                            Capacity = 20,
                            Latitude = 10.789999999999999,
                            Longitude = 106.63,
                            Name = "Tan Phu Station",
                            Status = "Active"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Kinh Duong Vuong",
                            Capacity = 25,
                            Latitude = 10.76,
                            Longitude = 106.59999999999999,
                            Name = "Binh Tan Station",
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("SaigonRideProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("None");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PassportStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Pending");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 0m,
                            Email = "admin@saigonride.com",
                            FullName = "System Admin",
                            IdentityImageUrl = "",
                            IdentityNumber = "000000000",
                            IdentityType = "CCCD",
                            IsLocked = false,
                            IsVerified = true,
                            PassportStatus = "Approved",
                            PasswordHash = "$2a$11$5UtYLRdUrCYrsxdDsWtuY.eUiVE9Rs2ugJQSE.al/OqZZak39owgy",
                            Role = "Admin",
                            UserType = "Local"
                        },
                        new
                        {
                            Id = 2,
                            Balance = 500000m,
                            Email = "nguyenvana@gmail.com",
                            FullName = "Nguyen Van A",
                            IdentityType = "None",
                            IsLocked = false,
                            IsVerified = true,
                            PassportStatus = "Pending",
                            PasswordHash = "$2a$11$kpylL.ksXcETF8Pv68w65.dSJ.Wx9C5u0zzi8gAXUDokip/eeAE3y",
                            Role = "User",
                            UserType = "Local"
                        },
                        new
                        {
                            Id = 3,
                            Balance = 300000m,
                            Email = "tranthib@gmail.com",
                            FullName = "Tran Thi B",
                            IdentityType = "None",
                            IsLocked = false,
                            IsVerified = true,
                            PassportStatus = "Pending",
                            PasswordHash = "$2a$11$keEGBTVGAAE5jQ6RM5/kDOzpQ2B0LGTlOZkaSaTdcHQzTjQjDq.GW",
                            Role = "User",
                            UserType = "Local"
                        },
                        new
                        {
                            Id = 4,
                            Balance = 1000000m,
                            Email = "johnsmith@gmail.com",
                            FullName = "John Smith",
                            IdentityType = "None",
                            IsLocked = false,
                            IsVerified = true,
                            PassportStatus = "Pending",
                            PasswordHash = "$2a$11$si0XBAfj49SDwJUTY.FT/OxK23Cp.PcLUi5Vjob4wBTiWXMMPY0zm",
                            Role = "User",
                            UserType = "Tourist"
                        },
                        new
                        {
                            Id = 5,
                            Balance = 800000m,
                            Email = "emilybrown@gmail.com",
                            FullName = "Emily Brown",
                            IdentityType = "None",
                            IsLocked = false,
                            IsVerified = true,
                            PassportStatus = "Pending",
                            PasswordHash = "$2a$11$oyuNqHg.Z0gdptJRh08KveGPQc4n2Vyetagn8rD.t2yNuOGEWNbeO",
                            Role = "User",
                            UserType = "Tourist"
                        });
                });

            modelBuilder.Entity("SaigonRideProject.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BatteryLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(100);

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerMinute")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatteryLevel = 90,
                            PlateNumber = "BK-001",
                            PricePerMinute = 500m,
                            StationId = 1,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 2,
                            BatteryLevel = 85,
                            PlateNumber = "BK-002",
                            PricePerMinute = 500m,
                            StationId = 1,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 3,
                            BatteryLevel = 70,
                            PlateNumber = "BK-003",
                            PricePerMinute = 500m,
                            StationId = 1,
                            Status = "InUse",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 4,
                            BatteryLevel = 95,
                            PlateNumber = "SC-001",
                            PricePerMinute = 1500m,
                            StationId = 1,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 5,
                            BatteryLevel = 40,
                            PlateNumber = "SC-002",
                            PricePerMinute = 1500m,
                            StationId = 1,
                            Status = "Maintenance",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 6,
                            BatteryLevel = 88,
                            PlateNumber = "BK-101",
                            PricePerMinute = 500m,
                            StationId = 2,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 7,
                            BatteryLevel = 92,
                            PlateNumber = "BK-102",
                            PricePerMinute = 500m,
                            StationId = 2,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 8,
                            BatteryLevel = 60,
                            PlateNumber = "BK-103",
                            PricePerMinute = 500m,
                            StationId = 2,
                            Status = "InUse",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 9,
                            BatteryLevel = 75,
                            PlateNumber = "SC-101",
                            PricePerMinute = 1500m,
                            StationId = 2,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 10,
                            BatteryLevel = 19,
                            PlateNumber = "SC-102",
                            PricePerMinute = 1500m,
                            StationId = 2,
                            Status = "Maintenance",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 11,
                            BatteryLevel = 90,
                            PlateNumber = "BK-201",
                            PricePerMinute = 500m,
                            StationId = 3,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 12,
                            BatteryLevel = 85,
                            PlateNumber = "BK-202",
                            PricePerMinute = 500m,
                            StationId = 3,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 13,
                            BatteryLevel = 80,
                            PlateNumber = "BK-203",
                            PricePerMinute = 500m,
                            StationId = 3,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 14,
                            BatteryLevel = 65,
                            PlateNumber = "SC-201",
                            PricePerMinute = 1500m,
                            StationId = 3,
                            Status = "InUse",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 15,
                            BatteryLevel = 95,
                            PlateNumber = "SC-202",
                            PricePerMinute = 1500m,
                            StationId = 3,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 16,
                            BatteryLevel = 88,
                            PlateNumber = "BK-301",
                            PricePerMinute = 500m,
                            StationId = 4,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 17,
                            BatteryLevel = 70,
                            PlateNumber = "BK-302",
                            PricePerMinute = 500m,
                            StationId = 4,
                            Status = "InUse",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 18,
                            BatteryLevel = 92,
                            PlateNumber = "BK-303",
                            PricePerMinute = 500m,
                            StationId = 4,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 19,
                            BatteryLevel = 10,
                            PlateNumber = "SC-301",
                            PricePerMinute = 1500m,
                            StationId = 4,
                            Status = "Maintenance",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 20,
                            BatteryLevel = 90,
                            PlateNumber = "SC-302",
                            PricePerMinute = 1500m,
                            StationId = 4,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 21,
                            BatteryLevel = 20,
                            PlateNumber = "BK-401",
                            PricePerMinute = 500m,
                            StationId = 5,
                            Status = "Maintenance",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 22,
                            BatteryLevel = 80,
                            PlateNumber = "BK-402",
                            PricePerMinute = 500m,
                            StationId = 5,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 23,
                            BatteryLevel = 85,
                            PlateNumber = "BK-403",
                            PricePerMinute = 500m,
                            StationId = 5,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 24,
                            BatteryLevel = 60,
                            PlateNumber = "SC-401",
                            PricePerMinute = 1500m,
                            StationId = 5,
                            Status = "InUse",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 25,
                            BatteryLevel = 95,
                            PlateNumber = "SC-402",
                            PricePerMinute = 1500m,
                            StationId = 5,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 26,
                            BatteryLevel = 90,
                            PlateNumber = "BK-501",
                            PricePerMinute = 500m,
                            StationId = 6,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 27,
                            BatteryLevel = 85,
                            PlateNumber = "BK-502",
                            PricePerMinute = 500m,
                            StationId = 6,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 28,
                            BatteryLevel = 80,
                            PlateNumber = "BK-503",
                            PricePerMinute = 500m,
                            StationId = 6,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 29,
                            BatteryLevel = 65,
                            PlateNumber = "SC-501",
                            PricePerMinute = 1500m,
                            StationId = 6,
                            Status = "InUse",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 30,
                            BatteryLevel = 95,
                            PlateNumber = "SC-502",
                            PricePerMinute = 1500m,
                            StationId = 6,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 31,
                            BatteryLevel = 88,
                            PlateNumber = "BK-601",
                            PricePerMinute = 500m,
                            StationId = 7,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 32,
                            BatteryLevel = 90,
                            PlateNumber = "BK-602",
                            PricePerMinute = 500m,
                            StationId = 7,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 33,
                            BatteryLevel = 85,
                            PlateNumber = "BK-603",
                            PricePerMinute = 500m,
                            StationId = 7,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 34,
                            BatteryLevel = 16,
                            PlateNumber = "SC-601",
                            PricePerMinute = 1500m,
                            StationId = 7,
                            Status = "Maintenance",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 35,
                            BatteryLevel = 95,
                            PlateNumber = "SC-602",
                            PricePerMinute = 1500m,
                            StationId = 7,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 36,
                            BatteryLevel = 90,
                            PlateNumber = "BK-701",
                            PricePerMinute = 500m,
                            StationId = 8,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 37,
                            BatteryLevel = 85,
                            PlateNumber = "BK-702",
                            PricePerMinute = 500m,
                            StationId = 8,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 38,
                            BatteryLevel = 80,
                            PlateNumber = "BK-703",
                            PricePerMinute = 500m,
                            StationId = 8,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 39,
                            BatteryLevel = 70,
                            PlateNumber = "SC-701",
                            PricePerMinute = 1500m,
                            StationId = 8,
                            Status = "InUse",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 40,
                            BatteryLevel = 95,
                            PlateNumber = "SC-702",
                            PricePerMinute = 1500m,
                            StationId = 8,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 41,
                            BatteryLevel = 88,
                            PlateNumber = "BK-801",
                            PricePerMinute = 500m,
                            StationId = 9,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 42,
                            BatteryLevel = 90,
                            PlateNumber = "BK-802",
                            PricePerMinute = 500m,
                            StationId = 9,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 43,
                            BatteryLevel = 85,
                            PlateNumber = "BK-803",
                            PricePerMinute = 500m,
                            StationId = 9,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 44,
                            BatteryLevel = 95,
                            PlateNumber = "SC-801",
                            PricePerMinute = 1500m,
                            StationId = 9,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 45,
                            BatteryLevel = 90,
                            PlateNumber = "SC-802",
                            PricePerMinute = 1500m,
                            StationId = 9,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 46,
                            BatteryLevel = 80,
                            PlateNumber = "BK-901",
                            PricePerMinute = 500m,
                            StationId = 10,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 47,
                            BatteryLevel = 85,
                            PlateNumber = "BK-902",
                            PricePerMinute = 500m,
                            StationId = 10,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 48,
                            BatteryLevel = 90,
                            PlateNumber = "BK-903",
                            PricePerMinute = 500m,
                            StationId = 10,
                            Status = "Available",
                            VehicleType = "Bike"
                        },
                        new
                        {
                            Id = 49,
                            BatteryLevel = 95,
                            PlateNumber = "SC-901",
                            PricePerMinute = 1500m,
                            StationId = 10,
                            Status = "Available",
                            VehicleType = "E-Scooter"
                        },
                        new
                        {
                            Id = 50,
                            BatteryLevel = 60,
                            PlateNumber = "SC-902",
                            PricePerMinute = 1500m,
                            StationId = 10,
                            Status = "InUse",
                            VehicleType = "E-Scooter"
                        });
                });

            modelBuilder.Entity("SaigonRideProject.Models.WalletTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WalletTransactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 9000m,
                            CreatedAt = new DateTime(2026, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Method = "MoMo",
                            Type = "Payment",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Amount = 15000m,
                            CreatedAt = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Method = "VNPay",
                            Type = "Payment",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Amount = 20000m,
                            CreatedAt = new DateTime(2026, 4, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Method = "ApplePay",
                            Type = "Payment",
                            UserId = 4
                        },
                        new
                        {
                            Id = 4,
                            Amount = 30000m,
                            CreatedAt = new DateTime(2026, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Method = "PayPal",
                            Type = "Payment",
                            UserId = 5
                        },
                        new
                        {
                            Id = 5,
                            Amount = 25000m,
                            CreatedAt = new DateTime(2026, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Method = "Cash",
                            Type = "Payment",
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            Amount = 40000m,
                            CreatedAt = new DateTime(2026, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Method = "Cash",
                            Type = "Payment",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("SaigonRideProject.Models.Payment", b =>
                {
                    b.HasOne("SaigonRideProject.Models.Rental", "Rental")
                        .WithMany("Payments")
                        .HasForeignKey("RentalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rental");
                });

            modelBuilder.Entity("SaigonRideProject.Models.Rental", b =>
                {
                    b.HasOne("SaigonRideProject.Models.Station", "PickupStation")
                        .WithMany()
                        .HasForeignKey("PickupStationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SaigonRideProject.Models.Station", "ReturnStation")
                        .WithMany()
                        .HasForeignKey("ReturnStationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SaigonRideProject.Models.User", "User")
                        .WithMany("Rentals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SaigonRideProject.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PickupStation");

                    b.Navigation("ReturnStation");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SaigonRideProject.Models.Vehicle", b =>
                {
                    b.HasOne("SaigonRideProject.Models.Station", "Station")
                        .WithMany("Vehicles")
                        .HasForeignKey("StationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Station");
                });

            modelBuilder.Entity("SaigonRideProject.Models.WalletTransaction", b =>
                {
                    b.HasOne("SaigonRideProject.Models.User", "User")
                        .WithMany("WalletTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SaigonRideProject.Models.Rental", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SaigonRideProject.Models.Station", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("SaigonRideProject.Models.User", b =>
                {
                    b.Navigation("Rentals");

                    b.Navigation("WalletTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
